import "./globals.css";
import { Roboto } from "next/font/google";
import Navbar from "./components/shared/navbar";
import Footer from "./components/shared/footer";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const roboto = Roboto({ weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <Navbar />
        <div className="px-6 mx-auto max-w-sm md:max-w-3xl">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
