import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <nav className="bg-sky-500 h-20 px-60 flex flex-row justify-between items-center">
            <Link href="/">ZHICONG</Link>
            <div>
              <Link href="/about" className="mx-8">About</Link>
              <Link href="/porfolio" className="mx-8">Portfolio</Link>
              <Link href="/contact" className="mx-8">Contact</Link>
            </div>
          </nav>
        {children}
      </body>
    </html>
  );
}
